# Generated by Django 6.0.3 on 2026-03-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
